templateDir: deutschland_templates # For local use: ./local/deutschland_templates
additionalProperties:
  packageName: "sensorcommunity"
  packageUrl: "https://github.com/t=huyeng/sensorcommunity"
  namespace: "deutschland"
  docLanguage: "de"
gitHost: "github.com"
gitUserId: "t-huyeng"
# gitRepoId: "<REPO-ID>"
files:
  pyproject.mustache:
    destinationFilename: pyproject.toml
    templateType: SupportingFiles
  requirements.txt: {}
  create_doc.mustache:
    destinationFilename: create_doc.py
    templateType: SupportingFiles
  rename_generated_code.mustache:
    destinationFilename: rename_generated_code.py
    templateType: SupportingFiles
  README.mustache:
    destinationFilename: README.md
    templateType: SupportingFiles
