# coding: utf-8

"""
    Sensor Community API

    This is the API for the Sensor Community. There are two domains where the same data is served.  https://api.luftdaten.info - This is optimized for receiving data. DON'T use this to request data.  https://data.sensor.community - This is faster and more reliable for serving data, so should be used for reporting cases. Where it is not supported for a certain endpoint, the previous domain must be used.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from test.paths.airrohr_v1_sensor_api_id.get import GetDataByApiId
from test.paths.static_v1_data_json.get import GetDataLast5Minutes
from test.paths.airrohr_v1_filter_query.get import GetSensorValuesWithFilter


class V1Api(
    GetDataByApiId,
    GetDataLast5Minutes,
    GetSensorValuesWithFilter,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
