# coding: utf-8

"""
    Sensor Community API

    This is the API for the Sensor Community. There are two domains where the same data is served.  https://api.luftdaten.info - This is optimized for receiving data. DON'T use this to request data.  https://data.sensor.community - This is faster and more reliable for serving data, so should be used for reporting cases. Where it is not supported for a certain endpoint, the previous domain must be used.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from test.paths.static_v2_data_1h_json.get import GetDataLast1Hour
from test.paths.static_v2_data_24h_json.get import GetDataLast24Hour
from test.paths.static_v2_data_json.get import GetDataLast5MinutesV2
from test.paths.static_v2_data_dust_min_json.get import GetDustDataLast5Minutes
from test.paths.static_v2_data_temp_min_json.get import GetTempHumAirDataLast5Minutes


class V2Api(
    GetDataLast1Hour,
    GetDataLast24Hour,
    GetDataLast5MinutesV2,
    GetDustDataLast5Minutes,
    GetTempHumAirDataLast5Minutes,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
