/**
 * Sensor Community API
 * This is the API for the Sensor Community. There are two domains where the same data is served.  https://api.luftdaten.info - This is optimized for receiving data. DON'T use this to request data.  https://data.sensor.community - This is faster and more reliable for serving data, so should be used for reporting cases. Where it is not supported for a certain endpoint, the previous domain must be used.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import V1Api from './api/V1Api';
import V2Api from './api/V2Api';


/**
* This_is_the_API_for_the_Sensor_Community__There_are_two_domains_where_the_same_data_is_served_https__api_luftdaten_info___This_is_optimized_for_receiving_data__DONT_use_this_to_request_data_https__data_sensor_community___This_is_faster_and_more_reliable_for_serving_data_so_should_be_used_for_reporting_cases__Where_it_is_not_supported_for_a_certain_endpoint_the_previous_domain_must_be_used_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SensorCommunityApi = require('index'); // See note below*.
* var xxxSvc = new SensorCommunityApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SensorCommunityApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SensorCommunityApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SensorCommunityApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
    * The V1Api service constructor.
    * @property {module:api/V1Api}
    */
    V1Api,

    /**
    * The V2Api service constructor.
    * @property {module:api/V2Api}
    */
    V2Api
};
