on: [push]
jobs:
  generate-javascript-client:
    runs-on: ubuntu-latest
    name: "Javascript Client"
    steps:
      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.3.0
        with:
          generator: javascript
          openapi-file: openapi.yaml
          # config-file: config.yml

      - name: "Print dir after generation"
        run: |
          echo "======================== Github Workspace ===================================="
          ls ${{ github.workspace }}
          echo "======================== Python Client ===================================="
          ls ${{ github.workspace }}/javascript-client
        shell: bash


      - name: "Install black and isort and use it to format code"
        run: |
          pip install black isort
          black ${{ github.workspace }}/javascript-client/
          isort  --profile black ${{ github.workspace }}/javascript-client/
        shell: bash

      - name: "Add and Commit files"
        run: |
          git status
          git pull
          git config --local user.email "bundesAPI@users.noreply.github.com"
          git config --local user.name "bundesbot"
          git add ${{ github.workspace }}/javascript-client
          git commit --allow-empty -m "Generate newest code from openapi.yaml" -a
        shell: bash

      - name: "Push changes"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.ref }}
